export type modelRetrieveCache = {
sector:string;
industry:string;
ticker:string;
earnings_f0:number;
earnings_f1:number;
earnings_f2:number;
growth_f1:number;
growth_f2:number;
pe_f0:number;
pe_f1:number;
pe_f2:number;
peg_f1:number;
peg_f2:number;
surprise_average:number;
nb_analysts_f1:number;
nb_analysts_f2:number;
high_to_low_eps_f1:number;
high_to_low_eps_f2:number;
fiscal_month:number;
volatility:number;
max_drawn_down:number;
occurrence:string;
max_price:number;
earnings_f0_industry_bench: number;
earnings_f1_industry_bench: number;
earnings_f2_industry_bench: number;
earnings_f0_sector_bench: number;
earnings_f1_sector_bench: number;
earnings_f2_sector_bench: number;
earnings_f0_delta_industry: number;
earnings_f1_delta_industry: number;
earnings_f2_delta_industry: number;
earnings_f0_delta_sector: number;
earnings_f1_delta_sector: number;
earnings_f2_delta_sector: number;
growth_f1_industry_bench: number;
growth_f2_industry_bench: number;
growth_f1_sector_bench: number;
growth_f2_sector_bench: number;
growth_f1_delta_industry: number;
growth_f2_delta_industry: number;
growth_f1_delta_sector: number;
growth_f2_delta_sector: number;
pe_f0_industry_bench: number;
pe_f1_industry_bench: number;
pe_f2_industry_bench: number;
pe_f0_sector_bench: number;
pe_f1_sector_bench: number;
pe_f2_sector_bench: number;
pe_f0_delta_industry: number;
pe_f1_delta_industry: number;
pe_f2_delta_industry: number;
pe_f0_delta_sector: number;
pe_f1_delta_sector: number;
pe_f2_delta_sector: number;
pe_f1_vs_f0 :number;
pe_f2_vs_f1 :number;
scoring_f0 :number;
scoring_f1 :number;
scoring_f2 :number;
surprise_average_industry_bench: number;
surprise_average_sector_bench: number
};