import type { RetrieveCacheModel } from './retrieve-cache.model';

export interface ScreenerColumn {
  key: keyof RetrieveCacheModel;
  label: string;
}

export const screenerColumns: ScreenerColumn[] = [
  { key: 'sector', label: 'Sector' },
  { key: 'industry', label: 'Industry' },
  { key: 'naics_title', label: 'NAICS Title' },
  { key: 'naics_code', label: 'NAICS Code' },
  { key: 'ticker', label: 'Ticker' },
  { key: 'earnings_f0', label: 'Earnings F0' },
  { key: 'earnings_f1', label: 'Earnings F1' },
  { key: 'earnings_f2', label: 'Earnings F2' },
  { key: 'growth_f1', label: 'Growth F1' },
  { key: 'growth_f2', label: 'Growth F2' },
  { key: 'pe_f0', label: 'PE F0' },
  { key: 'pe_f1', label: 'PE F1' },
  { key: 'pe_f2', label: 'PE F2' },
  { key: 'peg_f1', label: 'PEG F1' },
  { key: 'peg_f2', label: 'PEG F2' },
  { key: 'surprise_average', label: 'Surprise Average' },
  { key: 'nb_analysts_f1', label: 'Nb Analysts F1' },
  { key: 'nb_analysts_f2', label: 'Nb Analysts F2' },
  { key: 'high_to_low_eps_f1', label: 'High to Low EPS F1' },
  { key: 'high_to_low_eps_f2', label: 'High to Low EPS F2' },
  { key: 'fiscal_month', label: 'Fiscal Month' },
  { key: 'volatility', label: 'Volatility' },
  { key: 'max_drawn_down', label: 'Max Drawn Down' },
  { key: 'occurrence', label: 'Occurrence' },
  { key: 'max_price', label: 'Max Price' },
  { key: 'earnings_f0_industry_bench', label: 'Earnings F0 Industry Bench' },
  { key: 'earnings_f1_industry_bench', label: 'Earnings F1 Industry Bench' },
  { key: 'earnings_f2_industry_bench', label: 'Earnings F2 Industry Bench' },
  { key: 'earnings_f0_sector_bench', label: 'Earnings F0 Sector Bench' },
  { key: 'earnings_f1_sector_bench', label: 'Earnings F1 Sector Bench' },
  { key: 'earnings_f2_sector_bench', label: 'Earnings F2 Sector Bench' },
  { key: 'earnings_f0_naics_bench', label: 'Earnings F0 NAICS Bench' },
  { key: 'earnings_f1_naics_bench', label: 'Earnings F1 NAICS Bench' },
  { key: 'earnings_f2_naics_bench', label: 'Earnings F2 NAICS Bench' },
  { key: 'earnings_f0_delta_industry', label: 'Earnings F0 Delta Industry' },
  { key: 'earnings_f1_delta_industry', label: 'Earnings F1 Delta Industry' },
  { key: 'earnings_f2_delta_industry', label: 'Earnings F2 Delta Industry' },
  { key: 'earnings_f0_delta_sector', label: 'Earnings F0 Delta Sector' },
  { key: 'earnings_f1_delta_sector', label: 'Earnings F1 Delta Sector' },
  { key: 'earnings_f2_delta_sector', label: 'Earnings F2 Delta Sector' },
  { key: 'earnings_f0_delta_naics', label: 'Earnings F0 Delta NAICS' },
  { key: 'earnings_f1_delta_naics', label: 'Earnings F1 Delta NAICS' },
  { key: 'earnings_f2_delta_naics', label: 'Earnings F2 Delta NAICS' },
  { key: 'growth_f1_industry_bench', label: 'Growth F1 Industry Bench' },
  { key: 'growth_f2_industry_bench', label: 'Growth F2 Industry Bench' },
  { key: 'growth_f1_sector_bench', label: 'Growth F1 Sector Bench' },
  { key: 'growth_f2_sector_bench', label: 'Growth F2 Sector Bench' },
  { key: 'growth_f1_naics_bench', label: 'Growth F1 NAICS Bench' },
  { key: 'growth_f2_naics_bench', label: 'Growth F2 NAICS Bench' },
  { key: 'growth_f1_delta_industry', label: 'Growth F1 Delta Industry' },
  { key: 'growth_f2_delta_industry', label: 'Growth F2 Delta Industry' },
  { key: 'growth_f1_delta_sector', label: 'Growth F1 Delta Sector' },
  { key: 'growth_f2_delta_sector', label: 'Growth F2 Delta Sector' },
  { key: 'growth_f1_delta_naics', label: 'Growth F1 Delta NAICS' },
  { key: 'growth_f2_delta_naics', label: 'Growth F2 Delta NAICS' },
  { key: 'pe_f0_industry_bench', label: 'PE F0 Industry Bench' },
  { key: 'pe_f1_industry_bench', label: 'PE F1 Industry Bench' },
  { key: 'pe_f2_industry_bench', label: 'PE F2 Industry Bench' },
  { key: 'pe_f0_sector_bench', label: 'PE F0 Sector Bench' },
  { key: 'pe_f1_sector_bench', label: 'PE F1 Sector Bench' },
  { key: 'pe_f2_sector_bench', label: 'PE F2 Sector Bench' },
  { key: 'pe_f0_naics_bench', label: 'PE F0 NAICS Bench' },
  { key: 'pe_f1_naics_bench', label: 'PE F1 NAICS Bench' },
  { key: 'pe_f2_naics_bench', label: 'PE F2 NAICS Bench' },
  { key: 'pe_f0_delta_industry', label: 'PE F0 Delta Industry' },
  { key: 'pe_f1_delta_industry', label: 'PE F1 Delta Industry' },
  { key: 'pe_f2_delta_industry', label: 'PE F2 Delta Industry' },
  { key: 'pe_f0_delta_sector', label: 'PE F0 Delta Sector' },
  { key: 'pe_f1_delta_sector', label: 'PE F1 Delta Sector' },
  { key: 'pe_f2_delta_sector', label: 'PE F2 Delta Sector' },
  { key: 'pe_f0_delta_naics', label: 'PE F0 Delta NAICS' },
  { key: 'pe_f1_delta_naics', label: 'PE F1 Delta NAICS' },
  { key: 'pe_f2_delta_naics', label: 'PE F2 Delta NAICS' },
  { key: 'pe_f1_vs_f0', label: 'PE F1 vs F0' },
  { key: 'pe_f2_vs_f1', label: 'PE F2 vs F1' },
  { key: 'scoring_f0', label: 'Scoring F0' },
  { key: 'scoring_f1', label: 'Scoring F1' },
  { key: 'scoring_f2', label: 'Scoring F2' },
  { key: 'surprise_average_industry_bench', label: 'Surprise Average Industry Bench' },
  { key: 'surprise_average_sector_bench', label: 'Surprise Average Sector Bench' },
  { key: 'surprise_average_naics_bench', label: 'Surprise Average NAICS Bench' },
  { key: 'value_date_dmy', label: 'Value Date' }
];
